[package]
name = "rocket-in-action"
version = "0.1.0"
authors = ["huangqian <huangqian866@163.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"

[[example]]
name = "hello"
path = "examples/hello.rs"

[[example]]
name = "dynamic-path"
path = "examples/dynamic-path.rs"

